POST http://localhost:8080/processtdc
Content-Type: application/json

{
  "params": [
    {
      "name": "monto",
      "value": "700"
    },
    {
      "name": "exchange_rate",
      "value": "626"
    }
  ],
  "payload" : "CRC 234,193.35  \n USD 0.00  \n  CRC 162,057.10  \n  USD 952.19    \n CRC 166,570.45  \n USD 0.00 "
}

###

POST https://graal-function-vilz3brbpa-uc.a.run.app/processtdc/
Content-Type: application/json

{
  "params": [
    {
      "name": "monto",
      "value": "800"
    },
    {
      "name": "exchange_rate",
      "value": "677"
    }
  ],
  "payload" : "CRC 42,735.97    \n USD 0.00         \n CRC 92,919.20    \n USD 323.52       \n CRC 717,653.42   \n USD 32.59        \n CRC 0.00         \n USD 187.42       "
}

###

GET http://localhost:8080/getTime/