POST http://localhost:8080/processtdc/
Content-Type: application/json

{
  "params": [
    {
      "name": "monto",
      "value": "800"
    },
    {
      "name": "exchange_rate",
      "value": "500"
    }
  ],
  "payload" : "CRC 42,624.02  \n  USD 0.00 \n   CRC 65,407.65 \n   USD 290.04 \n  CRC 693,077.27 \n   USD 32.07 \n   CRC 502.95 \n   USD 184.57"
}

###

POST https://graal-function-vilz3brbpa-uc.a.run.app/processtdc/
Content-Type: application/json

{
  "params": [
    {
      "name": "monto",
      "value": "800"
    },
    {
      "name": "exchange_rate",
      "value": "677"
    }
  ],
  "payload" : "CRC 42,735.97    \n USD 0.00         \n CRC 92,919.20    \n USD 323.52       \n CRC 717,653.42   \n USD 32.59        \n CRC 0.00         \n USD 187.42       "
}

###

GET http://localhost:8080/getTime/